# Generated by Django 3.1.2 on 2020-11-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUTHOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30, null=True)),
                ('pubYear', models.CharField(max_length=4, null=True)),
                ('isbn', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LIBRARIAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('mName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
                ('streetAddr', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pinCode', models.CharField(max_length=6)),
                ('phoneNum', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubName', models.CharField(max_length=30)),
                ('streetAddr', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pinCode', models.CharField(max_length=6)),
                ('phoneNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffEmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('mName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
                ('streetAddr', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pinCode', models.CharField(max_length=6)),
                ('phoneNum', models.CharField(max_length=10)),
                ('USN', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('ISE', 'Information Science Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('sem', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
            ],
        ),
        migrations.CreateModel(
            name='WRITTENBY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorID', models.ManyToManyField(to='libraryApp.AUTHOR')),
                ('bookID', models.ManyToManyField(to='libraryApp.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCopies', models.IntegerField()),
                ('bookID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryApp.book')),
                ('librarianID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.librarian')),
            ],
        ),
        migrations.CreateModel(
            name='BORROWEDBOOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOut', models.DateTimeField(auto_now_add=True, null=True)),
                ('dueDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('checkIn', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.book')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='librarianID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.librarian'),
        ),
        migrations.AddField(
            model_name='book',
            name='pubID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryApp.publisher'),
        ),
    ]
