# Generated by Django 3.1.2 on 2020-11-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_defaultvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='checkIn',
            field=models.DateTimeField(null=True),
        ),
    ]
