# Generated by Django 3.1.2 on 2020-12-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_auto_20201223_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorName',
            field=models.CharField(help_text='Author name', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='authorID',
            field=models.ManyToManyField(help_text='Authors', to='libraryApp.AUTHOR'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookTitle',
            field=models.CharField(help_text='Book Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('ELE', 'Electronics'), ('TC', 'Telecommunication'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('MEC', 'Mechanics'), ('EVS', 'Environmental Science'), ('BIO', 'Bioengineering'), ('BUS', 'Business Skills')], help_text='Category', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='International Standard Book Number', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='librarianID',
            field=models.ForeignKey(help_text='Librarian ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.librarian'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubID',
            field=models.ForeignKey(help_text='Publisher ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryApp.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.CharField(help_text='Year of publication', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='bookID',
            field=models.ForeignKey(help_text='Book ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='checkIn',
            field=models.DateTimeField(blank=True, help_text='Check in date', null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='checkOut',
            field=models.DateTimeField(auto_now_add=True, help_text='Check out date', null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='dueDate',
            field=models.DateTimeField(blank=True, help_text='Due date', null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='userID',
            field=models.ForeignKey(help_text='User ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.user'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='district',
            field=models.CharField(help_text='District', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phoneNum',
            field=models.CharField(help_text='Phone number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pinCode',
            field=models.CharField(help_text='PIN Code', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pubName',
            field=models.CharField(help_text='Publisher name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(help_text='State', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='streetAddr',
            field=models.CharField(help_text='Street Address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bookCopies',
            field=models.PositiveSmallIntegerField(help_text='Number of the Book copies', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bookID',
            field=models.OneToOneField(help_text='Book ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryApp.book'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='librarianID',
            field=models.ForeignKey(help_text='Librarian ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.librarian'),
        ),
    ]
