# Generated by Django 3.1.2 on 2020-12-24 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0003_auto_20201223_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='userID',
            field=models.ForeignKey(help_text='User ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bookCopies',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of the Book copies'),
        ),
    ]
