# Generated by Django 3.1.2 on 2020-12-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_auto_20201129_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='lName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='mName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
