# Generated by Django 3.1.2 on 2020-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_auto_20201204_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
