# Generated by Django 3.1.2 on 2020-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0007_auto_20201204_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvalues',
            name='coursesAll',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='genreAll',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
