# Generated by Django 3.1.2 on 2020-12-26 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0007_auto_20201225_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LIBRARIAN',
        ),
        migrations.DeleteModel(
            name='USER',
        ),
        migrations.AlterField(
            model_name='book',
            name='librarianID',
            field=models.ForeignKey(help_text='Librarian ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='userID',
            field=models.ForeignKey(help_text='User ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='librarianID',
            field=models.ForeignKey(help_text='Librarian ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
