# Generated by Django 3.1.2 on 2020-12-29 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_auto_20201226_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phoneNum',
            field=models.CharField(help_text='Phone number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phoneNum', message='Enter a valid Phone Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pinCode',
            field=models.CharField(help_text='PIN Code', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_pinCode', message='Enter a valid Postal Identification Number', regex='[0-9]{6}')]),
        ),
    ]
