# Generated by Django 3.1.2 on 2020-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_auto_20201204_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultvalues',
            name='coursesAll',
        ),
        migrations.RemoveField(
            model_name='defaultvalues',
            name='genreAll',
        ),
    ]
