# Generated by Django 3.1.2 on 2020-12-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_auto_20201204_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
