# Generated by Django 3.1.2 on 2020-12-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_auto_20201229_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='defaultValues',
        ),
    ]
