# Generated by Django 3.1.2 on 2020-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0010_auto_20201208_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtenby',
            name='dateAdded',
        ),
        migrations.AlterField(
            model_name='librarian',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='A valid email address, please.', max_length=254),
        ),
    ]
