# Generated by Django 3.1.2 on 2020-12-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0011_auto_20201215_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorID',
            field=models.ManyToManyField(to='libraryApp.AUTHOR'),
        ),
        migrations.DeleteModel(
            name='WRITTENBY',
        ),
    ]
