# Generated by Django 3.1.2 on 2020-12-16 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0012_auto_20201216_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bookCopies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
