# Generated by Django 3.1.2 on 2020-12-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pinCode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='streetAddr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
