# Generated by Django 3.1.2 on 2020-12-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201222_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('fName', models.CharField(help_text='first name', max_length=20)),
                ('mName', models.CharField(help_text='middle name', max_length=20)),
                ('lName', models.CharField(help_text='last name', max_length=20)),
                ('streetAddr', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('pinCode', models.CharField(max_length=6, null=True)),
                ('phoneNum', models.CharField(max_length=10, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('USN', models.CharField(max_length=10, null=True, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
