# Generated by Django 3.1.2 on 2020-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sem',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
