# Generated by Django 3.1.2 on 2020-12-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201223_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='USN',
        ),
        migrations.RemoveField(
            model_name='account',
            name='course',
        ),
        migrations.RemoveField(
            model_name='account',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sem',
        ),
    ]
