# Generated by Django 3.1.2 on 2020-12-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201223_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='USN',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sem',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
