# Generated by Django 3.1.2 on 2020-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201223_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.CharField(choices=[('ISE', 'Information Science Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('ETE', 'Electronics and Telecommunication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIV', 'Civil Engineering'), ('MCA', 'Master of Computer Applications'), ('AI&ML', 'Artificial Intelligence and Machine Learning')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sem',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
