# Generated by Django 3.1.2 on 2020-12-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201223_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='USN',
            field=models.CharField(blank=True, help_text='University Serial Number', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.CharField(blank=True, choices=[('ISE', 'Information Science Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('ETE', 'Electronics and Telecommunication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIV', 'Civil Engineering'), ('MCA', 'Master of Computer Applications'), ('AI&ML', 'Artificial Intelligence and Machine Learning')], help_text='Branch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.CharField(help_text='District', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='Email id', max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fName',
            field=models.CharField(help_text='First name', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='lName',
            field=models.CharField(blank=True, help_text='Last name', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='mName',
            field=models.CharField(blank=True, help_text='Middle name', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNum',
            field=models.CharField(blank=True, help_text='Phone number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pinCode',
            field=models.CharField(help_text='PIN Code', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sem',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], help_text='Semester', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(help_text='State', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(help_text='Username', max_length=30, unique=True),
        ),
    ]
