# Generated by Django 3.1.2 on 2020-12-26 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201227_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNum',
            field=models.CharField(blank=True, help_text='Phone number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phoneNum', message='Enter a valid Phone Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='pinCode',
            field=models.CharField(help_text='PIN Code', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_pinCode', message='Enter a valid Postal Identification Number', regex='[0-9]{6}')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_salary', message='Enter a valid Salary', regex='[0-9]{6}')]),
        ),
    ]
