# Generated by Django 3.1.2 on 2020-12-27 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201227_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_salary', message='Enter a valid Salary', regex='[0-9]{5,6}')]),
        ),
    ]
